apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-{{ .Values.env }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-{{ .Values.env }}
  minReplicas: {{ .Values.autoScale.minReplicas }}
  maxReplicas: {{ .Values.autoScale.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoScale.targetCPUUtilizationPercentage }}