apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.env }}-svc
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
    {{ if eq .Values.env "canary" -}}
    env: {{ .Values.env }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http