apiVersion: v1
kind: Service
metadata:
  name: {{ template "microservice-service-deployment.fullname" . }}-service
  labels:
    app: {{ template "microservice-service-deployment.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "microservice-service-deployment.name" . }}
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http