apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-{{ .Values.env }}"
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    version: {{ .Values.app.image.tag }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        env: {{ .Values.env }}
        release: {{ .Release.Name }}
        version: {{ .Values.app.image.tag }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.app.image.repository }}/{{ .Values.app.image.imageName }}:{{ .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        env:
        {{- range $index, $item := .Values.configs }}  #looping through values in ConfigMap
          - name: {{ $item.name }}
            valueFrom:
              configMapKeyRef:
                name: configs
                key: {{ $item.key }}
        {{- end }}
        ports:
          - name: {{ .Values.app.port.name }}
            containerPort: {{ .Values.app.port.containerPort }}
            protocol: {{ .Values.app.port.protocol }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true

      initContainers:
      - name: keyvault-agent
        image: {{ .Values.hexadite.image.repository }}/{{ .Values.hexadite.image.imageName }}:{{ .Values.hexadite.image.tag }}
        env:
        - name: VAULT_BASE_URL
          value: {{ .Values.hexadite.keyVault }}
        - name: SERVICE_PRINCIPLE_FILE_PATH
          value: /host/azure.json
        - name: SECRETS_FOLDER
          value: /secrets
        - name: SECRETS_KEYS
          value: mt-aad-password
        volumeMounts:
        - name: secrets
          mountPath: /secrets
        - name: host-sp
          mountPath: /host/azure.json
          readOnly: true

      imagePullSecrets:
        - name: {{ .Values.app.imagePullSecrets }}

      volumes:
      - name: secrets
        emptyDir:
          # we want the secrets to reside only in-memory
          medium: Memory
      - name: host-sp
        hostPath:
          # this file contains the cluster service-principal, it exists on every node by default
          path: /etc/kubernetes/azure.json
          #type: File # commented out because current cubctl doesn't understand it.
