# Default values for microservice-service-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configmap:
  aadAppId: 9b86d78b-3ee5-4502-a10b-46bd378b784f
  appInsightsKey: a50ad6fc-04a4-41b2-b597-85965be4cd6c
  jwtKey: olji4eoj30p8km4poij4mk520-jw3j
  omsWorkspaceId: 06cebcb7-1a47-4d43-a9a3-8bb950ceec16
  secretsVaultUrl: https://ivanbny-mt-svc-kv.vault.azure.net
  
app:
  replicaCount: 3
  image:
    repository: acrmicroserviceswestus.azurecr.io # ACR Login Server
    imageName: containerized-microservices-pipeline-service
    tag: canary
    pullPolicy: Always
  imagePullSecrets: acr-credentials
  cpu: "500m"

autoScale:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

hexadite:
  image:
    repository: acrmicroserviceswestus.azurecr.io
    imageName: hexadite
    tag: latest
  keyVault: https://microservices-deploy-kv.vault.azure.net/

service:
  type: ClusterIP
  port: 80
  targetPort: 4201