# Default values for microservice-service-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: login-service
env: production

app:
  replicaCount: 3
  image:
    repository: acrmicrok8eastus.azurecr.io # ACR Login Server
    imageName: containerized-microservices-pipeline-service
    tag: "1.0.1" # override on cli using --set app.image.tag=<version>
    pullPolicy: Always
  imagePullSecrets: acr-credentials
  cpu: "500m"

autoScale:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

hexadite:
  image:
    repository: acrmicrok8eastus.azurecr.io
    imageName: hexadite
    tag: latest
  keyVault: https://microk8-deploy-kv.vault.azure.net/

service:
  type: ClusterIP
  port: 80
  targetPort: 4201