apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  AadAppId: "{{ .Values.configmap.aadAppId }}"
  AadPasswordFilePath: "{{ .Values.configmap.aadPasswordFilePath }}"
  ApplicationInsights.InstrumentationKey: "{{ .Values.configmap.appInsightsKey }}"
  CorsOrigins: "*"
  JwtAudience: "http://microsoft.com"
  JwtExpireMinutes: "30"
  JwtIssuer: "http://microsoft.com"
  Logging.Console.LogLevel.Default: Warning
  Logging.Debug.LogLevel.Default: Warning
  Logging.IncludeScopes: "false"
  OMS.WorkspaceID: "{{ .Values.configmap.omsWorkspaceId }}"
  SecretsVaultUrl: "{{ .Values.configmap.secretsVaultUrl }}"
  SqlConnectionString: "{{ .Values.configmap.sqlConnectionString }}"