# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: login-service
env: production

configmap:
  name: configs
  # Azure Active Directory App registration ID
  aadAppId:
  # Application Insights Key
  appInsightsKey:
  # Azure Key Vault URL
  secretsVaultUrl:
  # File path to Azure Active Directory password file in container
  aadPasswordFilePath: "/secrets/secrets/mt-aad-password"

app:
  replicaCount: 3
  image:
    # ACR Server URL
    repository: acrmicrok8seastus.azurecr.io
    imageName: containerized-microservices-pipeline-service
    tag: "1.0.14"
    pullPolicy: Always
  port:
    name: http
    containerPort: 80
    protocol: TCP
  imagePullSecrets: acr-credentials

# Each Container has a request of 0.25 cpu and 64MiB (226 bytes) of memory. 
# Each Container has a limit of 0.5 cpu and 128MiB of memory. 
# If a pod has two containers, you can say the Pod has a request of 0.5 cpu 
# and 128 MiB of memory, and a limit of 1 cpu and 256MiB of memory.
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

autoScale:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

hexadite:
  image:
    repository: acrmicrok8seastus.azurecr.io               # ACR Server URL
    imageName: hexadite
    tag: latest
  keyVault: https://microk8s-deploy-kv.vault.azure.net/    # Azure Key Vault URL

connectionStringSecretName: db-secret
connectionStringSecretKey: connection-string

# Config map keys to set as environment variables in each container
configs:
  - name: ApplicationInsights__InstrumentationKey
    key: ApplicationInsights.InstrumentationKey
  - name: JwtIssuer
    key: JwtIssuer
  - name: JwtAudience
    key: JwtAudience
  - name: CorsOrigins
    key: CorsOrigins
  - name: SecretsVaultUrl
    key: SecretsVaultUrl
  - name: AadPasswordFilePath
    key: AadPasswordFilePath
  - name: AadAppId
    key: AadAppId   

service:
  type: ClusterIP
  port: 80
  targetPort: 4201